% Script for analysing the files generated by craft
clear variables
directory = 'D:\HoloICE\MyHolosuite\Results\Glass beads\10 - New beads\Optronis 2um\Seq3\contrast_seq0001';

files.classification = 'classification_class.mat'; % File with the output of all the predictors and the hand chosen class of the particles
files.tree = 'tree.mat';
files.wholeTree = 'whole_tree.mat';
files.classification_cD = 'whol_cD.mat';

load(fullfile(directory, files.classification_cD))